//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webb_GruppK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personchannel
    {
        public int personchannelid { get; set; }
        public int FK_personid { get; set; }
        public int FK_channelid { get; set; }
    
        public virtual channel channel { get; set; }
        public virtual person person { get; set; }
    }
}
