

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Webb_GruppK.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TvEntities : DbContext
{
    public TvEntities()
        : base("name=TvEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<channel> channels { get; set; }

    public virtual DbSet<person> people { get; set; }

    public virtual DbSet<personchannel> personchannels { get; set; }

    public virtual DbSet<program> programs { get; set; }

}

}

